/**
 * Curated manufacturer suggestions per component type — brand names only,
 * for normalized selection (later dedupe basis together with mpn). Free-text
 * entry stays possible for anything missing.
 */
import type { ComponentType } from '@/lib/componentCatalog';

export const MANUFACTURERS: Record<ComponentType, readonly string[]> = {
  bullet: [
    'Barnes',
    'Berger',
    'Berry’s',
    'Campro',
    'Fiocchi',
    'GECO',
    'H&N',
    'Hornady',
    'Lapua',
    'LOS',
    'Norma',
    'Nosler',
    'PPU (Prvi Partizan)',
    'Remington',
    'RWS',
    'Sellier & Bellot',
    'Sierra',
    'Speer',
    'Winchester',
  ],
  powder: [
    'Accurate',
    'Alliant',
    'Explosia (Lovex)',
    'Hodgdon',
    'IMR',
    'Norma',
    'Ramshot',
    'Reload Swiss',
    'Rottweil',
    'Vihtavuori',
    'Winchester',
  ],
  primer: [
    'CCI',
    'Federal',
    'Fiocchi',
    'Ginex',
    'Magtech',
    'Murom',
    'Remington',
    'RWS',
    'Sellier & Bellot',
    'Winchester',
  ],
  case: [
    'Alpha Munitions',
    'Federal',
    'GECO',
    'Hornady',
    'Lapua',
    'Norma',
    'Peterson',
    'PPU (Prvi Partizan)',
    'Remington',
    'RWS',
    'Sellier & Bellot',
    'Starline',
    'Winchester',
  ],
};
